# Generated by Django 2.2.9 on 2020-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyKel',
            fields=[
                ('key_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('key_from', models.DateField(blank=True, null=True)),
                ('key_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
